### ISSUE TITLE
Post comments are not shown

### ISSUE THREAD

**Issue by sxe** [rystaf/mlmym#107]
Comments on posts are not shown anymore. 

Random example: https://old.lemmy.zip/post/19430126 shows 8 comments which are not visible.

Happens on all posts as far as I can tell. 

Comments are visible on other front ends.

Cheers

**Comment by rystaf** [comment]
I haven't been able to reproduce this yet. When I click the link I can see all the comments. I believe your issue is caused by a bad cookie. Clearing you site data would fix it, but before you do that can you share a screen shot of what cookies you have saved? If the jwt cookie is saved be sure to blur that out or remove it before screenshotting it, that's your session token.
You can see your current cookies in firefox by pressing Ctrl+Shift+I then going to the Storage tab and making sure "https://old.lemmy.zip" is selected under Cookies. On Chrome it's the same except it's in the Application tab
![image](https://github.com/user-attachments/assets/73bf8f85-98b5-4a0e-9761-b6c0b9646703)

**Comment by sxe** [comment]
![2024-07-20_17-57](https://github.com/user-attachments/assets/60e0a8fa-966b-4a65-b66c-434493ba2c22)
Here sure, here you go. 
Haven't delete the cookies yet so if you need anything else I am happy to check it.

**Comment by rystaf** [comment]
Thank you! Looks like it's the DefaultCommentSortType cookie. "Scaled" isn't a [valid sort type for comments](https://join-lemmy.org/api/types/CommentSortType.html). Not sure how that got set like that, weird. If you delete just that one it should fix your issue.

**Comment by sxe** [comment]
AH nice, yes deleting that cookie fixed it. Appreciate it!
Have a nice weekend, case closed.
